[package]
name = "esp-idf-hal"
version = "0.1.0"
edition = "2018"

[dependencies]
bitflags = "1"
esp-idf-bindgen = "0.1"
embedded-hal = { version = "0.2", features = ["unproven"] }
static_assertions = "1"
macaddr = "1"
memchr = "2"
libc = { version = "0.2", default-features = false }
