on: [pull_request, push]

name: CI

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: azohra/shell-linter@v0.3.0
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Fetch Cross Repository
        id: fetch_cross
        run: |
          pushd "$(mktemp -d)"

          git clone -b xtensa https://github.com/reitermarkus/cross .

          echo "::set-output name=cross_dir::$(pwd)"
          echo "::set-output name=cross_version::$(git rev-parse HEAD)"
      - name: Cache Cross
        uses: actions/cache@v1
        with:
          path: ${{ steps.fetch_cross.outputs.cross_dir }}/target
          key: cross-${{ steps.fetch_cross.outputs.cross_version }}
      - name: Install Cross & Build Docker Image
        run: |
          pushd '${{ steps.fetch_cross.outputs.cross_dir }}'

          cargo install --path . --force

          pushd docker

          docker pull '${{ github.actor }}/cross:xtensa-esp32-none-elf' || true

          docker build \
            --cache-from '${{ github.actor }}/cross:xtensa-esp32-none-elf' \
            -t '${{ github.actor }}/cross:xtensa-esp32-none-elf' \
            -f Dockerfile.xtensa-esp32-none-elf \
            .
      - name: Fetch Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set ESP IDF Version
        id: set_esp_idf_version
        run: echo "::set-output name=esp_idf_version::$(git rev-parse @:esp-idf)"
      - name: Cache ESP IDF Tools
        uses: actions/cache@v1
        with:
          path: target/esp-idf-tools
          key: esp-idf-tools-${{ steps.set_esp_idf_version.outputs.esp_idf_version }}
      - name: Build Project
        run: ./build.sh
      - name: Log into Docker Hub
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ github.actor }}' --password-stdin
      - name: Push Docker Image
        run: docker push '${{ github.actor }}/cross:xtensa-esp32-none-elf'
